//! PBL (Planetary Boundary Layer) and atmospheric state structures.
//!
//! Ported from `hanna_mod.f90` and `com_mod.f90` (ust, wst, hmix, ol, etc.).
//! Contains turbulence parameters needed for the Hanna (1982) scheme,
//! which drives stochastic velocity fluctuations in the Langevin equation.

use bytemuck::{Pod, Zeroable};
use ndarray::Array2;

/// Per-particle turbulence parameters from the Hanna (1982) scheme.
///
/// Corresponds to the module-level variables in `hanna_mod.f90`:
///   `ust, wst, ol, h, zeta, sigu, sigv, sigw, dsigwdz, dsigw2dz, tlu, tlv, tlw`
///
/// These are computed from the local PBL state at each particle's position and
/// used to drive stochastic turbulent velocity fluctuations in the Langevin
/// equation (Thomson 1987).
///
/// Layout is `#[repr(C)]` and padded to 64 bytes (16 × f32) for GPU vec4
/// alignment.
#[repr(C)]
#[derive(Clone, Copy, Debug, Pod, Zeroable)]
pub struct HannaParams {
    /// Friction velocity u* \[m/s\] — characterises mechanical turbulence
    /// generated by surface shear stress.
    pub ust: f32,
    /// Convective velocity scale w* \[m/s\] — characterises buoyancy-driven
    /// turbulence; zero in stable conditions.
    pub wst: f32,
    /// Obukhov length L \[m\] — ratio of mechanical to buoyant turbulence
    /// production. Positive in stable, negative in unstable conditions.
    pub ol: f32,
    /// Mixing height h \[m\] — depth of the turbulent boundary layer.
    pub h: f32,
    /// Stability parameter ζ = z/L — dimensionless height scaled by Obukhov
    /// length; governs the shape of turbulence profiles.
    pub zeta: f32,
    /// Standard deviation of u-velocity fluctuations `σ_u` \[m/s\].
    pub sigu: f32,
    /// Standard deviation of v-velocity fluctuations `σ_v` \[m/s\].
    pub sigv: f32,
    /// Standard deviation of w-velocity fluctuations `σ_w` \[m/s\].
    pub sigw: f32,
    /// Vertical gradient of `σ_w` \[s⁻¹\]: `dσ_w/dz`.
    pub dsigwdz: f32,
    /// Vertical gradient of `σ_w²` \[m/s\]: `d(σ_w²)/dz`.
    pub dsigw2dz: f32,
    /// Lagrangian decorrelation timescale for u \[s\].
    pub tlu: f32,
    /// Lagrangian decorrelation timescale for v \[s\].
    pub tlv: f32,
    /// Lagrangian decorrelation timescale for w \[s\].
    pub tlw: f32,
    /// Padding to reach 16 × f32 = 64 bytes for GPU vec4 alignment.
    #[allow(clippy::pub_underscore_fields)]
    pub _pad: [f32; 3],
}

// ---------------------------------------------------------------------------
// Stability classification
// ---------------------------------------------------------------------------

/// Atmospheric stability classification derived from the Obukhov length.
///
/// The Obukhov length L encodes the relative importance of mechanical
/// vs. buoyant turbulence production:
///
/// | Regime   | L           | 1/L        |
/// |----------|-------------|------------|
/// | Stable   | L > 0       | 1/L > 0    |
/// | Unstable | L < 0       | 1/L < 0    |
/// | Neutral  | \|L\| → ∞   | 1/L → 0    |
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum StabilityClass {
    /// Stable stratification — buoyancy suppresses turbulence (L > 0).
    Stable,
    /// Neutral — mechanical turbulence dominates (|L| very large).
    Neutral,
    /// Unstable / convective — buoyancy enhances turbulence (L < 0).
    Unstable,
}

/// Threshold on |L| \[m\] above which conditions are classified as neutral.
const NEUTRAL_OL_THRESHOLD: f32 = 1.0e5;

/// Threshold on |1/L| \[m⁻¹\] below which conditions are classified as neutral.
const NEUTRAL_OLI_THRESHOLD: f32 = 1.0e-5;

impl StabilityClass {
    /// Classify stability from Obukhov length L \[m\].
    ///
    /// Very large |L| (> 10⁵ m) or zero is treated as neutral.
    #[must_use]
    pub fn from_obukhov_length(ol: f32) -> Self {
        if ol == 0.0 || ol.abs() > NEUTRAL_OL_THRESHOLD {
            Self::Neutral
        } else if ol > 0.0 {
            Self::Stable
        } else {
            Self::Unstable
        }
    }

    /// Classify stability from inverse Obukhov length 1/L \[m⁻¹\].
    ///
    /// This is the form stored in the FLEXPART met fields (`oli` in
    /// `com_mod.f90`). Very small |1/L| (< 10⁻⁵) is treated as neutral.
    #[must_use]
    pub fn from_inverse_obukhov(oli: f32) -> Self {
        if oli.abs() < NEUTRAL_OLI_THRESHOLD {
            Self::Neutral
        } else if oli > 0.0 {
            Self::Stable
        } else {
            Self::Unstable
        }
    }
}

// ---------------------------------------------------------------------------
// Gridded PBL state
// ---------------------------------------------------------------------------

/// Gridded PBL fields from meteorological input data.
///
/// These 2-D fields are interpolated from ECMWF (or other met model) output
/// and correspond to the surface/PBL arrays in `com_mod.f90` lines 420–448.
/// Each field has dimensions `(nx, ny)` matching the meteorological grid.
#[derive(Clone, Debug)]
pub struct PblState {
    /// Friction velocity u* \[m/s\] — `ustar` in `com_mod.f90`.
    pub ustar: Array2<f32>,
    /// Convective velocity scale w* \[m/s\] — `wstar` in `com_mod.f90`.
    pub wstar: Array2<f32>,
    /// Mixing height \[m\] — `hmix` in `com_mod.f90`.
    pub hmix: Array2<f32>,
    /// Inverse Obukhov length 1/L \[m⁻¹\] — `oli` in `com_mod.f90`.
    pub oli: Array2<f32>,
    /// Surface sensible heat flux \[W/m²\] — `sshf` in `com_mod.f90`.
    pub sshf: Array2<f32>,
    /// Surface solar radiation \[W/m²\] — `ssr` in `com_mod.f90`.
    pub ssr: Array2<f32>,
    /// Surface stress \[N/m²\] — `surfstr` in `com_mod.f90`.
    pub surfstr: Array2<f32>,
}

impl PblState {
    /// Allocate a zeroed `PblState` for a grid of size `(nx, ny)`.
    #[must_use]
    pub fn new(nx: usize, ny: usize) -> Self {
        Self {
            ustar: Array2::zeros((nx, ny)),
            wstar: Array2::zeros((nx, ny)),
            hmix: Array2::zeros((nx, ny)),
            oli: Array2::zeros((nx, ny)),
            sshf: Array2::zeros((nx, ny)),
            ssr: Array2::zeros((nx, ny)),
            surfstr: Array2::zeros((nx, ny)),
        }
    }

    /// Grid dimensions `(nx, ny)`.
    #[must_use]
    pub fn shape(&self) -> (usize, usize) {
        let s = self.ustar.shape();
        (s[0], s[1])
    }

    /// Classify stability at grid point `(i, j)` from the inverse Obukhov length.
    #[must_use]
    pub fn stability_at(&self, i: usize, j: usize) -> StabilityClass {
        StabilityClass::from_inverse_obukhov(self.oli[[i, j]])
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn hanna_params_size_and_alignment() {
        assert_eq!(std::mem::size_of::<HannaParams>(), 64);
        assert_eq!(std::mem::align_of::<HannaParams>(), 4);
    }

    #[test]
    fn hanna_params_zeroed() {
        let p = HannaParams::zeroed();
        assert_eq!(p.ust, 0.0);
        assert_eq!(p.wst, 0.0);
        assert_eq!(p.tlw, 0.0);
    }

    #[test]
    fn hanna_params_bytemuck_roundtrip() {
        let mut p = HannaParams::zeroed();
        p.ust = 0.3;
        p.h = 1500.0;
        p.sigw = 1.2;
        let bytes: &[u8] = bytemuck::bytes_of(&p);
        let recovered: &HannaParams = bytemuck::from_bytes(bytes);
        assert_eq!(recovered.ust, 0.3);
        assert_eq!(recovered.h, 1500.0);
        assert_eq!(recovered.sigw, 1.2);
    }

    // -- Stability from Obukhov length L -----------------------------------

    #[test]
    fn stability_from_ol_stable() {
        assert_eq!(
            StabilityClass::from_obukhov_length(100.0),
            StabilityClass::Stable
        );
        assert_eq!(
            StabilityClass::from_obukhov_length(10.0),
            StabilityClass::Stable
        );
    }

    #[test]
    fn stability_from_ol_unstable() {
        assert_eq!(
            StabilityClass::from_obukhov_length(-100.0),
            StabilityClass::Unstable
        );
        assert_eq!(
            StabilityClass::from_obukhov_length(-50.0),
            StabilityClass::Unstable
        );
    }

    #[test]
    fn stability_from_ol_neutral() {
        assert_eq!(
            StabilityClass::from_obukhov_length(1e6),
            StabilityClass::Neutral,
        );
        assert_eq!(
            StabilityClass::from_obukhov_length(-2e6),
            StabilityClass::Neutral,
        );
        assert_eq!(
            StabilityClass::from_obukhov_length(0.0),
            StabilityClass::Neutral,
        );
    }

    // -- Stability from inverse Obukhov length 1/L -------------------------

    #[test]
    fn stability_from_oli_stable() {
        assert_eq!(
            StabilityClass::from_inverse_obukhov(0.01),
            StabilityClass::Stable
        );
        assert_eq!(
            StabilityClass::from_inverse_obukhov(0.1),
            StabilityClass::Stable
        );
    }

    #[test]
    fn stability_from_oli_unstable() {
        assert_eq!(
            StabilityClass::from_inverse_obukhov(-0.01),
            StabilityClass::Unstable
        );
        assert_eq!(
            StabilityClass::from_inverse_obukhov(-0.1),
            StabilityClass::Unstable
        );
    }

    #[test]
    fn stability_from_oli_neutral() {
        assert_eq!(
            StabilityClass::from_inverse_obukhov(1e-6),
            StabilityClass::Neutral,
        );
        assert_eq!(
            StabilityClass::from_inverse_obukhov(-1e-7),
            StabilityClass::Neutral,
        );
        assert_eq!(
            StabilityClass::from_inverse_obukhov(0.0),
            StabilityClass::Neutral,
        );
    }

    // -- Consistency: L and 1/L should agree --------------------------------

    #[test]
    fn stability_ol_and_oli_consistent() {
        for ol in [50.0_f32, -200.0, 1e6, -1e6] {
            let from_ol = StabilityClass::from_obukhov_length(ol);
            let from_oli = StabilityClass::from_inverse_obukhov(1.0 / ol);
            assert_eq!(from_ol, from_oli, "mismatch for L = {ol}");
        }
    }

    // -- PblState -----------------------------------------------------------

    #[test]
    fn pbl_state_construction() {
        let pbl = PblState::new(10, 20);
        assert_eq!(pbl.shape(), (10, 20));
        assert_eq!(pbl.ustar[[0, 0]], 0.0);
        assert_eq!(pbl.hmix[[9, 19]], 0.0);
    }

    #[test]
    fn pbl_state_stability_at() {
        let mut pbl = PblState::new(3, 3);
        pbl.oli[[0, 0]] = 0.05; // stable
        pbl.oli[[1, 1]] = -0.05; // unstable
        pbl.oli[[2, 2]] = 0.0; // neutral

        assert_eq!(pbl.stability_at(0, 0), StabilityClass::Stable);
        assert_eq!(pbl.stability_at(1, 1), StabilityClass::Unstable);
        assert_eq!(pbl.stability_at(2, 2), StabilityClass::Neutral);
    }
}
